(display "Basic collatz fun - recursive scheme function\n")
(define (r n)
  (display (string-append (number->string n) "\n"))
  (if (= 1 n) 1 (r (if (= 1 (modulo n 2)) (+ (* n 3) 1) (/ n 2)))))
(r 15)
