#!/usr/bin/env bash

## commit-msg that prefixes all commit messages with a ticket number
## Taken from the branch name. Works when adhering to the git-flow
## Naming conventions (hotfix|feature/<ticketno>)


if [ $# -lt 1 ]; then
    echo "No commit message"
    exit 1
fi

# Skip merge commits, otherwise, all the commented out lines will be added
hooks_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ -f "${hooks_dir}/../MERGE_MSG" ]; then
    exit 0
fi
current_branch=$(git branch | grep '*' | awk '{print $2}')
if [[ "$current_branch" =~ ^[[:alpha:]]+/([[:alpha:]]{3,4}-[[:digit:]]+) ]]; then
    ticket="${BASH_REMATCH[1]}"
    [[ $(cat "$1" | grep -q "$ticket") ]] || echo "$ticket:" $(cat "$1") > "$1"
fi
