#!/usr/bin/env bash
########################
##  Simple lint hook  ##
##  for PHP scripts   ##
########################
ERROR_COLOUR='\e[0;31m'
MSG_COLOUR='\e[0;33m'
END_COLOUR='\e[0m'

DisplayError() {
    echo -e "${ERROR_COLOUR}Syntax error in file $f ${END_COLOUR}"
    exit_code=1
}
exit_code=0
for f in $(git status | grep .php | awk '{print $NF;}'); do
    php -l "$f" 1> /dev/null
    [ $? -eq 0 ] || DisplayError
done

if [ $exit_code -ne 0 ]; then
    echo -e "${MSG_COLOUR}Commit aborted${END_COLOUR}"
fi

exit $exit_code
